### PR TITLE
bump base upper bound to <4.19

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
CI seems busted. 😢

**Comment by treeowl** [comment]
We'll have to see if it recovers or if we need to regenerate with `haskell-ci` to catch up with whatever.

**Comment by mitchellwrosen** [comment]
Sounds good. I went ahead and added another commit here just to see what this looks like with a `haskell-ci github pqueue.cabal`-generated CI config. We can remove that commit before merging if we'd like.

**Comment by treeowl** [comment]
We already have a Haskell CI workflow. Let's see what CI does this time, but if the new one works, you should revert that commit and use `haskell-ci regenerate` instead to replace the old one instead of adding another.

**Comment by mitchellwrosen** [comment]
Sure; I'll just revert the commits then. I saw the existing CI file, but it looked hand-written, and I thought `haskell-ci` would be an improvement.

Feel free to add more commits to this PR, or not - I'm stepping away from it for now.

**Comment by treeowl** [comment]
Sorry if I got it wrong. I was just trying to advise. It looks like you did a good thing....

**Comment by treeowl** [comment]
It looks like I did get it wrong.  If that was from haskell-ci, it was way too old. Ugh. Sorry.

**Comment by mitchellwrosen** [comment]
I think this PR is good to merge; here's one green run from history: https://github.com/lspitzner/pqueue/actions/runs/4433666369

To fix CI I simply removed `7.10.3` from `Tested-With`, as it seems ghcup has trouble installing that one. But that can be another PR.

**Comment by treeowl** [comment]
Okay, thanks a lot. I'll try to remember to do the CI thing and make a release in the morning.

**Comment by mitchellwrosen** [comment]
No problem, thank you!

**Comment by treeowl** [comment]
It looks like whatever problem you encountered with 7.10.3 was temporary (maybe a server issue or something). I didn't have any trouble with it in #91, so I guess we'll keep supporting 7.10.3 a bit longer.

**Comment by konsumlamm** [comment]
> It looks like whatever problem you encountered with 7.10.3 was temporary (maybe a server issue or something). I didn't have any trouble with it in #91, so I guess we'll keep supporting 7.10.3 a bit longer.

I think the issue is that installing 7.10.3 via GHCup no longer works (by default), which is what the old CI used (via `haskell/actions/setup`). The new CI uses `hvr-ppa` instead.

**Comment by ocharles** [comment]
Could we get this released to Hackage, or at least a Hackage revision?

**Comment by treeowl** [comment]
Yeah, let's just make a release and deal with the remaining equality question later.

**Comment by ocharles** [comment]
The what? I don't see any mention of equality here?

**Comment by konsumlamm** [comment]
The equality question is https://github.com/lspitzner/pqueue/issues/78. See also https://github.com/lspitzner/pqueue/issues/121.

**Pull request merged**
