### PR TITLE
Please release this version to Hackage.

### PR DESCRIPTION
**Pull request by thielema**
I will continue with 1.3.3
where I add modules with key order as type parameter.

### CODE REVIEW

**Comment by lspitzner** [comment]
I made one testcase fail on purpose, and `cabal test` says

> ~~~~
> Preprocessing test suite 'test' for pqueue-1.3.2.2...
> Running 1 test suites...
> Test suite test: RUNNING...
> +++ OK, passed 100 tests.
> [..]
> +++ OK, passed 100 tests.
> *** Failed! Falsifiable (after 1 test): 
> *** Exception running callback: 
> user error (Test failed to pass)
> Test suite test: PASS
> Test suite logged to: dist/test/pqueue-1.3.2.2-test.log
> 1 of 1 test suites (1 of 1 test cases) passed.
> ~~~~

Not sure what makes this pass..

**Comment by thielema** [comment]
On Sun, 12 Mar 2017, Lennart Spitzner wrote:

> I made one testcase fail on purpose, and cabal test says
> 
> Preprocessing test suite 'test' for pqueue-1.3.2.2...
> Running 1 test suites...
> Test suite test: RUNNING...
> +++ OK, passed 100 tests.
> [..]
> +++ OK, passed 100 tests.
> *** Failed! Falsifiable (after 1 test): 
> *** Exception running callback: 
> user error (Test failed to pass)
> Test suite test: PASS
> Test suite logged to: dist/test/pqueue-1.3.2.2-test.log
> 1 of 1 test suites (1 of 1 test cases) passed.
> 
> Not sure what makes this pass..

The test-suite tests only functions from PQueue.Min and it does not test 
all functions. It is the version I found in the old repository.

**Comment by lspitzner** [comment]
No, I made a testcase fail. Like, I inverted one of the quickcheck properties.

**Comment by lspitzner** [comment]
ah, https://gist.github.com/mbbx6spp/1343429

**Comment by lspitzner** [comment]
Fixed and released.

**Pull request merged**
